# <b> Домашнее задание </b>

<b>Задание 1.</b> Создайте массив, который состоит из целых чисел от -50 до 50 включительно. Затем удалите последние 25 элеметов массива. Затем разверните массив. Добавьте в конец массива 999. Создайте новый массив в который войдут все четные числа из ранее полученного массива и напечатайте его.

In [30]:
# решение
arr=list(range(-50,51,1))
x=[]

a=(len(arr)-25)
while len(arr)>a:
   
   arr.pop()
arr.append(999)

for i in list(arr):
    if i%2==0:
        x.append(str(i))
print (','.join(x),)


-50,-48,-46,-44,-42,-40,-38,-36,-34,-32,-30,-28,-26,-24,-22,-20,-18,-16,-14,-12,-10,-8,-6,-4,-2,0,2,4,6,8,10,12,14,16,18,20,22,24


<b>Задание 2.</b> Даны несколько массивов целых чисел (A, B, C, D). Напишите программный код, с помощью которого вы сможете определить длину самой длинной непрерывной последовательности равных значений для каждого из массивов.

In [25]:
# [1, 1, 1, 2, 3, 4, 5, 6, 3, 4, 1, 1, 1, 1] - самая длинная последовательность длины 4
A = [1] * 20 + [1, 1, 3] * 30 + [1] * 21

B = list(range(1, 9, 2)) * 3 + list(range(4, 1, 1)) * 2 + [3] * 3
B.pop()
B.reverse()
B.pop()
B.reverse()

C = [b - 2 for b in B]
C.reverse()
C =  A + C

D = [777] + [666] + [1,2,1,1] * 2 + [1,1,1,1,3]*3 + [1, 4] * 2

E = [1, 1, 1, 2, 3, 4, 5, 6, 3, 4, 1, 1, 1, 1]

def lengh(E):
    max = 1
    count = 1
    for i in range(len(E)-1):
        if E[i]==E[i+1]:
            count+=1
            if count>max:
                max=count
        else:
            count=1
    return max;
print(lengh(A))
print(lengh(B))
print(lengh(C))
print(lengh(D))
print(lengh(E))

22
2
23
6
4


<b>Задание 3.</b> Напишите функция, которая на вход принимает прямоугольную матрицу и возвращает транспонированную матрицу. Протестируйте функцию на матрицах A, B, C.

In [12]:
A = [[1, 1], [1, 0]]
B = [[2, 3, 4], [4, 5, 6], [7, -1, -2], [-4, -6, 99], [1, 0, 1]]
C = [[1, 2, 3, 4, 5]]

import numpy as np

arr_matrix = np.array(B) #Меняем матрицу для проверки,я проверил все.
arr_transpose = np.transpose(arr_matrix)

print(arr_matrix)
print("\n")
print(arr_transpose)

[[ 2  3  4]
 [ 4  5  6]
 [ 7 -1 -2]
 [-4 -6 99]
 [ 1  0  1]]


[[ 2  4  7 -4  1]
 [ 3  5 -1 -6  0]
 [ 4  6 -2 99  1]]
